# Site settings
title: Shubham Sharma
description: Shubham Sharma
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shubham Sharma
user_description: Hi! I am a Information Technology Engineering undergraduate currently in the third year.
user_title: Full Stack Web Developer
email: shubham.31996@gmail.com
twitter_username: shubh_shrma_
github_username: shubhshrma
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
